import { create } from 'zustand'
import { SLOT_DEF_TOTALS, makeSlotCfg, INIT_ZONES } from '../constants'

const clone = x => JSON.parse(JSON.stringify(x))

const useSimStore = create((set) => ({
  // Project
  projectName: localStorage.getItem('exsim_projectName') || null,
  projectInput: '',
  scenarioName: localStorage.getItem('exsim_scenarioName') || '시나리오 1',
  // UI
  tab: 'build',
  zones: clone(INIT_ZONES),
  selZoneId: null,
  editZone: null,
  editMediaUid: null,
  activeMediaUid: null,
  editingZoneName: false,
  simStatus: 'idle',
  slot: 0,
  speed: 1,
  canvasZoom: 1.0,
  flowType: 'guided',
  circularFlow: false,
  palOpen: false,
  slotCfgs: SLOT_DEF_TOTALS.map(makeSlotCfg),
  simRange: { start: 0, end: 0 },
  slotResults: [],
  simLogs: (() => { try { return JSON.parse(localStorage.getItem('exsim_logs') || '[]') } catch { return [] } })(),
  reportData: null,
  heatTimeline: [],
  heatScrubIdx: 0,
  runningSlot: 0,
  viewFloor: 0,
  floorCount: 1,
  floorSizes: [{ w: 20, h: 14 }],
  tmpSize: { w: 20, h: 14 },
  dispStats: {
    mediaCount: 0, totalCap: '-', curVisitors: '0명', avgDwell: '-',
    bottlenecks: '0건', skipRate: '0%', skipRateNum: 0, engIdx: '-',
    density: '-', densityNum: 0,
    totalVisitors: 0, totalEngaged: 0,
    flowEff: '-', flowEffNum: 0,
    engRate: '-', engRateNum: 0,
    congestion: '0초', congestionSec: 0,
  },
  skipTable: [],
  heatZoneStats: [],
  heatMainView: 'all',   // 'all' | 'heatmap' | 'zones' | 'media'
  heatPopupZone: null,       // { zoneId, x, y } — 클릭된 존 팝업
  confirmModal: { visible: false, title: '', message: '', onConfirm: null },

  // Setters
  setProjectName: (v) => set({ projectName: v }),
  setProjectInput: (v) => set({ projectInput: v }),
  setScenarioName: (v) => set({ scenarioName: v }),
  setTab: (v) => set({ tab: v }),
  setZones: (v) => set(s => ({ zones: typeof v === 'function' ? v(s.zones) : v })),
  setSelZoneId: (v) => set({ selZoneId: v }),
  setEditZone: (v) => set(s => ({ editZone: typeof v === 'function' ? v(s.editZone) : v })),
  setEditMediaUid: (v) => set({ editMediaUid: v }),
  setActiveMediaUid: (v) => set({ activeMediaUid: v }),
  setEditingZoneName: (v) => set({ editingZoneName: v }),
  setSimStatus: (v) => set({ simStatus: v }),
  setSlot: (v) => set({ slot: v }),
  setSpeed: (v) => set({ speed: v }),
  setCanvasZoom: (v) => set(s => ({ canvasZoom: typeof v === 'function' ? v(s.canvasZoom) : v })),
  setFlowType: (v) => set({ flowType: v }),
  setCircularFlow: (v) => set({ circularFlow: v }),
  setPalOpen: (v) => set(s => ({ palOpen: typeof v === 'function' ? v(s.palOpen) : v })),
  setSlotCfgs: (v) => set(s => ({ slotCfgs: typeof v === 'function' ? v(s.slotCfgs) : v })),
  setSimRange: (v) => set(s => ({ simRange: typeof v === 'function' ? v(s.simRange) : v })),
  setSlotResults: (v) => set(s => ({ slotResults: typeof v === 'function' ? v(s.slotResults) : v })),
  setSimLogs: (v) => set(s => ({ simLogs: typeof v === 'function' ? v(s.simLogs) : v })),
  setReportData: (v) => set({ reportData: v }),
  setHeatTimeline: (v) => set(s => ({ heatTimeline: typeof v === 'function' ? v(s.heatTimeline) : v })),
  setHeatScrubIdx: (v) => set({ heatScrubIdx: v }),
  setRunningSlot: (v) => set({ runningSlot: v }),
  setViewFloor: (v) => set({ viewFloor: v }),
  setFloorCount: (v) => set({ floorCount: v }),
  setFloorSizes: (v) => set(s => ({ floorSizes: typeof v === 'function' ? v(s.floorSizes) : v })),
  setTmpSize: (v) => set(s => ({ tmpSize: typeof v === 'function' ? v(s.tmpSize) : v })),
  setDispStats: (v) => set(s => ({ dispStats: typeof v === 'function' ? v(s.dispStats) : v })),
  setSkipTable: (v) => set({ skipTable: v }),
  setHeatZoneStats: (v) => set({ heatZoneStats: v }),
  setHeatMainView: (v) => set({ heatMainView: v }),
  setHeatPopupZone: (v) => set({ heatPopupZone: v }),
  setConfirmModal: (v) => set(s => ({ confirmModal: typeof v === 'function' ? v(s.confirmModal) : v })),
}))

export default useSimStore
